# Generated by Django 5.2.5 on 2025-08-26 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('primary_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedules', to='scheduling.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alternative_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.classroom')),
                ('alternative_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.teacher')),
                ('alternative_time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.timeslot')),
                ('backup_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='scheduling.backupschedule')),
                ('original_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='scheduling.scheduleitem')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='scheduling.schedule')),
            ],
        ),
    ]
